# Generated by Django 4.2.9 on 2025-02-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_companyassets_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandboxcompany',
            name='alpha',
        ),
        migrations.RemoveField(
            model_name='sandboxcompany',
            name='saved_alpha',
        ),
        migrations.AddField(
            model_name='sandboxasset',
            name='alpha',
            field=models.DecimalField(decimal_places=8, default=0.001, max_digits=14, verbose_name='alpha'),
        ),
        migrations.AddField(
            model_name='sandboxasset',
            name='grafico',
            field=models.CharField(choices=[('Malware', 'Malware'), ('Phishing', 'Phishing'), ('DDoS', 'DDoS'), ('Geral', 'Geral')], default='Geral', max_length=255, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='sandboxasset',
            name='saved_alpha',
            field=models.DecimalField(decimal_places=8, default=0.001, max_digits=14, verbose_name='alpha'),
        ),
    ]
