# Generated by Django 4.2.9 on 2025-06-11 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_role', models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor')], max_length=10, verbose_name='Requested Role')),
                ('current_role', models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor')], max_length=10, verbose_name='Current Role')),
                ('justification', models.TextField(help_text='Please explain why you want to change your role', verbose_name='Justification')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Change Request',
                'verbose_name_plural': 'Role Change Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
